name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Remplacez "main" par la branche principale de votre dépôt

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifiez le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installez Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Assurez-vous que cette version correspond à celle utilisée par votre projet

      # Étape 3 : Naviguez dans le dossier du projet
      - name: Navigate to project folder
        working-directory: ./v1
        run: echo "Navigating to v1 folder"

      # Étape 4 : Installez les dépendances
      - name: Install dependencies
        working-directory: ./v1
        run: npm install

      # Étape 5 : Construisez le projet
      - name: Build project
        working-directory: ./v1
        run: npm run build

      # Étape 6 : Déployez sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./v1/dist # Chemin mis à jour pour correspondre à votre structure